### ISSUE TITLE
Add version command

### ISSUE THREAD

**Issue by ursuscamp** [ursuscamp/nomen#18]
Add a version command to the indexer's CLI

**Comment by HakanVardarr** [comment]
Do you want the version to be hard coded? Or do you have an idea that I can work?

**Comment by ursuscamp** [comment]
You can use `env!("CARGO_PKG_VERSION")` to get the version from the build system. That's the same thing the [stats](https://nomenexplorer.com/stats) page gets it.

**Comment by HakanVardarr** [comment]
Oh ok thanks I will work on that.

**Comment by HakanVardarr** [comment]
Should I write version command as a subcommand or a option?

**Comment by ursuscamp** [comment]
Subcommand

**Comment by ursuscamp** [comment]
Thanks, @HakanVardarr. Merged #28
