### ISSUE TITLE
Do OP_RETURNs start with NOM?

### ISSUE THREAD

**Issue by melvincarvalho** [ursuscamp/nomen#4]
Doesnt seem to be in the spec.

But is here:

![image](https://github.com/ursuscamp/nomen/assets/65864/db1bdb23-5091-4ce5-9b57-698b9853209d)

https://blockstream.info/tx/def9c21a4760f0488a6eec703a9beb522a1e883af2cd2b2b2b5486fffb608c18?expand

**Comment by ursuscamp** [comment]
They do. This will need to be corrected. Thanks for pointing it out.

**Comment by ursuscamp** [comment]
Fixed in #10
